### PR TITLE
Add AWS compliance documentation

### PR DESCRIPTION
**Pull request by joshmyers**

### CODE REVIEW

**Review by markyjones — CHANGES_REQUESTED** [review]
Just the copywriting date, also need you to add the correct pay-team team permissions into the repo if they are not already there

**Comment by joshmyers** [comment]
@markyjones comment addressed.

**Review by markyjones — APPROVED** [review]
All good now comments addressed.

**Review by markyjones — APPROVED** [review]
Looks good

**Comment by markyjones** [comment]
@joshmyers I cannot review it as I don't have write permissions. Have you added the pay team group membership s required in the guide I wrote?

**Comment by joshmyers** [comment]
All the payments groups have been added.

**Pull request merged**
